# Generate Unity Scene YAML for Hexagon Arena
import math

# Read positions from file
tile_data = []
with open('hex_arena_output.txt', 'r') as f:
    for line in f:
        line = line.strip()
        if line and not line.startswith('#'):
            parts = line.split(',')
            if len(parts) >= 6:
                idx = int(parts[0])
                q = int(parts[1])
                r = int(parts[2])
                layer = int(parts[3])
                x = float(parts[4])
                y = float(parts[5])
                z = float(parts[6])
                tile_data.append((idx, q, r, layer, x, y, z))

print(f"Loaded {len(tile_data)} tiles")

# Generate YAML
yaml_lines = []
yaml_lines.append("%YAML 1.1")
yaml_lines.append("%TAG !u! tag:unity3d.com,2011:")
yaml_lines.append("--- !u!29 &1")
yaml_lines.append("OcclusionCullingSettings:")
yaml_lines.append("  m_ObjectHideFlags: 0")
yaml_lines.append("  serializedVersion: 2")
yaml_lines.append("  m_OcclusionBakeSettings:")
yaml_lines.append("    smallestOccluder: 5")
yaml_lines.append("    smallestHole: 0.25")
yaml_lines.append("    backfaceThreshold: 100")
yaml_lines.append("  m_SceneGUID: 00000000000000000000000000000000")
yaml_lines.append("  m_OcclusionCullingData: {fileID: 0}")
yaml_lines.append("--- !u!104 &2")
yaml_lines.append("RenderSettings:")
yaml_lines.append("  m_ObjectHideFlags: 0")
yaml_lines.append("  serializedVersion: 10")
yaml_lines.append("  m_Fog: 0")
yaml_lines.append("  m_FogColor: {r: 0.5, g: 0.5, b: 0.5, a: 1}")
yaml_lines.append("  m_FogMode: 3")
yaml_lines.append("  m_FogDensity: 0.01")
yaml_lines.append("  m_LinearFogStart: 0")
yaml_lines.append("  m_LinearFogEnd: 300")
yaml_lines.append("  m_AmbientSkyColor: {r: 0.212, g: 0.227, b: 0.259, a: 1}")
yaml_lines.append("  m_AmbientEquatorColor: {r: 0.114, g: 0.125, b: 0.133, a: 1}")
yaml_lines.append("  m_AmbientGroundColor: {r: 0.047, g: 0.043, b: 0.035, a: 1}")
yaml_lines.append("  m_AmbientIntensity: 1")
yaml_lines.append("  m_AmbientMode: 0")
yaml_lines.append("  m_SubtractiveShadowColor: {r: 0.42, g: 0.478, b: 0.627, a: 1}")
yaml_lines.append("  m_SkyboxMaterial: {fileID: 10304, guid: 0000000000000000f000000000000000, type: 0}")
yaml_lines.append("  m_HaloStrength: 0.5")
yaml_lines.append("  m_FlareStrength: 1")
yaml_lines.append("  m_FlareFadeSpeed: 3")
yaml_lines.append("  m_HaloTexture: {fileID: 0}")
yaml_lines.append("  m_SpotCookie: {fileID: 10001, guid: 0000000000000000e000000000000000, type: 0}")
yaml_lines.append("  m_DefaultReflectionMode: 0")
yaml_lines.append("  m_DefaultReflectionResolution: 128")
yaml_lines.append("  m_ReflectionBounces: 1")
yaml_lines.append("  m_ReflectionIntensity: 1")
yaml_lines.append("  m_CustomReflection: {fileID: 0}")
yaml_lines.append("  m_Sun: {fileID: 0}")
yaml_lines.append("  m_UseRadianceAmbientProbe: 0")
yaml_lines.append("--- !u!157 &3")
yaml_lines.append("LightmapSettings:")
yaml_lines.append("  m_ObjectHideFlags: 0")
yaml_lines.append("  serializedVersion: 13")
yaml_lines.append("  m_BakeOnSceneLoad: 0")
yaml_lines.append("  m_GISettings:")
yaml_lines.append("    serializedVersion: 2")
yaml_lines.append("    m_BounceScale: 1")
yaml_lines.append("    m_IndirectOutputScale: 1")
yaml_lines.append("    m_AlbedoBoost: 1")
yaml_lines.append("    m_EnvironmentLightingMode: 0")
yaml_lines.append("    m_EnableBakedLightmaps: 1")
yaml_lines.append("    m_EnableRealtimeLightmaps: 0")
yaml_lines.append("  m_LightmapEditorSettings:")
yaml_lines.append("    serializedVersion: 12")
yaml_lines.append("    m_Resolution: 2")
yaml_lines.append("    m_BakeResolution: 40")
yaml_lines.append("    m_AtlasSize: 1024")
yaml_lines.append("    m_AO: 0")
yaml_lines.append("    m_CompAOExponent: 1")
yaml_lines.append("    m_CompAOExponentDirect: 0")
yaml_lines.append("    m_ExtractAmbientOcclusion: 0")
yaml_lines.append("    m_Padding: 2")
yaml_lines.append("    m_LightmapParameters: {fileID: 0}")
yaml_lines.append("    m_LightmapsBakeMode: 1")
yaml_lines.append("    m_TextureCompression: 1")
yaml_lines.append("    m_ReflectionCompression: 2")
yaml_lines.append("    m_MixedBakeMode: 2")
yaml_lines.append("    m_BakeBackend: 2")
yaml_lines.append("    m_PVRSampling: 1")
yaml_lines.append("    m_PVRDirectSampleCount: 32")
yaml_lines.append("    m_PVRSampleCount: 512")
yaml_lines.append("    m_PVRBounces: 2")
yaml_lines.append("    m_PVREnvironmentSampleCount: 256")
yaml_lines.append("    m_PVREnvironmentReferencePointCount: 2048")
yaml_lines.append("    m_PVRFilteringMode: 1")
yaml_lines.append("    m_PVRDenoiserTypeDirect: 1")
yaml_lines.append("    m_PVRDenoiserTypeIndirect: 1")
yaml_lines.append("    m_PVRDenoiserTypeAO: 1")
yaml_lines.append("    m_PVRFilterTypeDirect: 0")
yaml_lines.append("    m_PVRFilterTypeIndirect: 0")
yaml_lines.append("    m_PVRFilterTypeAO: 0")
yaml_lines.append("    m_PVREnvironmentMIS: 1")
yaml_lines.append("    m_PVRCulling: 1")
yaml_lines.append("    m_PVRFilteringGaussRadiusDirect: 1")
yaml_lines.append("    m_PVRFilteringGaussRadiusIndirect: 1")
yaml_lines.append("    m_PVRFilteringGaussRadiusAO: 1")
yaml_lines.append("    m_PVRFilteringAtrousPositionSigmaDirect: 0.5")
yaml_lines.append("    m_PVRFilteringAtrousPositionSigmaIndirect: 2")
yaml_lines.append("    m_PVRFilteringAtrousPositionSigmaAO: 1")
yaml_lines.append("    m_ExportTrainingData: 0")
yaml_lines.append("    m_TrainingDataDestination: TrainingData")
yaml_lines.append("    m_LightProbeSampleCountMultiplier: 4")
yaml_lines.append("  m_LightingDataAsset: {fileID: 20201, guid: 0000000000000000f000000000000000, type: 0}")
yaml_lines.append("  m_LightingSettings: {fileID: 0}")
yaml_lines.append("--- !u!196 &4")
yaml_lines.append("NavMeshSettings:")
yaml_lines.append("  serializedVersion: 2")
yaml_lines.append("  m_ObjectHideFlags: 0")
yaml_lines.append("  m_BuildSettings:")
yaml_lines.append("    serializedVersion: 3")
yaml_lines.append("    agentTypeID: 0")
yaml_lines.append("    agentRadius: 0.5")
yaml_lines.append("    agentHeight: 2")
yaml_lines.append("    agentSlope: 45")
yaml_lines.append("    agentClimb: 0.4")
yaml_lines.append("    ledgeDropHeight: 0")
yaml_lines.append("    maxJumpAcrossDistance: 0")
yaml_lines.append("    minRegionArea: 2")
yaml_lines.append("    manualCellSize: 0")
yaml_lines.append("    cellSize: 0.16666667")
yaml_lines.append("    manualTileSize: 0")
yaml_lines.append("    tileSize: 256")
yaml_lines.append("    buildHeightMesh: 0")
yaml_lines.append("    maxJobWorkers: 0")
yaml_lines.append("    preserveTilesOutsideBounds: 0")
yaml_lines.append("    debug:")
yaml_lines.append("      m_Flags: 0")
yaml_lines.append("  m_NavMeshData: {fileID: 0}")

# ID counters for objects
# HexTile IDs: 1000000xxx (xxx = tile index * 10)
# Container: 399977391

# Directional Light
yaml_lines.append("--- !u!1 &247249173")
yaml_lines.append("GameObject:")
yaml_lines.append("  m_ObjectHideFlags: 0")
yaml_lines.append("  m_CorrespondingSourceObject: {fileID: 0}")
yaml_lines.append("  m_PrefabInstance: {fileID: 0}")
yaml_lines.append("  m_PrefabAsset: {fileID: 0}")
yaml_lines.append("  serializedVersion: 6")
yaml_lines.append("  m_Component:")
yaml_lines.append("  - component: {fileID: 247249175}")
yaml_lines.append("  - component: {fileID: 247249174}")
yaml_lines.append("  m_Layer: 0")
yaml_lines.append("  m_Name: Directional Light")
yaml_lines.append("  m_TagString: Untagged")
yaml_lines.append("  m_Icon: {fileID: 0}")
yaml_lines.append("  m_NavMeshLayer: 0")
yaml_lines.append("  m_StaticEditorFlags: 0")
yaml_lines.append("  m_IsActive: 1")
yaml_lines.append("--- !u!108 &247249174")
yaml_lines.append("Light:")
yaml_lines.append("  m_ObjectHideFlags: 0")
yaml_lines.append("  m_CorrespondingSourceObject: {fileID: 0}")
yaml_lines.append("  m_PrefabInstance: {fileID: 0}")
yaml_lines.append("  m_PrefabAsset: {fileID: 0}")
yaml_lines.append("  m_GameObject: {fileID: 247249173}")
yaml_lines.append("  m_Enabled: 1")
yaml_lines.append("  serializedVersion: 12")
yaml_lines.append("  m_Type: 1")
yaml_lines.append("  m_Color: {r: 1, g: 0.95686275, b: 0.8392157, a: 1}")
yaml_lines.append("  m_Intensity: 1")
yaml_lines.append("  m_Range: 10")
yaml_lines.append("  m_SpotAngle: 30")
yaml_lines.append("  m_InnerSpotAngle: 21.80208")
yaml_lines.append("  m_CookieSize2D: {x: 0.5, y: 0.5}")
yaml_lines.append("  m_Shadows:")
yaml_lines.append("    m_Type: 2")
yaml_lines.append("    m_Resolution: -1")
yaml_lines.append("    m_CustomResolution: -1")
yaml_lines.append("    m_Strength: 1")
yaml_lines.append("    m_Bias: 0.05")
yaml_lines.append("    m_NormalBias: 0.4")
yaml_lines.append("    m_NearPlane: 0.2")
yaml_lines.append("  m_Cookie: {fileID: 0}")
yaml_lines.append("  m_DrawHalo: 0")
yaml_lines.append("  m_Flare: {fileID: 0}")
yaml_lines.append("  m_RenderMode: 0")
yaml_lines.append("  m_CullingMask:")
yaml_lines.append("    serializedVersion: 2")
yaml_lines.append("    m_Bits: 4294967295")
yaml_lines.append("  m_RenderingLayerMask: 1")
yaml_lines.append("  m_Lightmapping: 4")
yaml_lines.append("  m_LightShadowCasterMode: 0")
yaml_lines.append("  m_AreaSize: {x: 1, y: 1}")
yaml_lines.append("  m_BounceIntensity: 1")
yaml_lines.append("  m_ColorTemperature: 6570")
yaml_lines.append("  m_UseColorTemperature: 0")
yaml_lines.append("  m_UseViewFrustumForShadowCasterCull: 1")
yaml_lines.append("--- !u!4 &247249175")
yaml_lines.append("Transform:")
yaml_lines.append("  m_ObjectHideFlags: 0")
yaml_lines.append("  m_CorrespondingSourceObject: {fileID: 0}")
yaml_lines.append("  m_PrefabInstance: {fileID: 0}")
yaml_lines.append("  m_PrefabAsset: {fileID: 0}")
yaml_lines.append("  m_GameObject: {fileID: 247249173}")
yaml_lines.append("  serializedVersion: 2")
yaml_lines.append("  m_LocalRotation: {x: 0.40821788, y: -0.23456968, z: 0.10938163, w: 0.8754261}")
yaml_lines.append("  m_LocalPosition: {x: 0, y: 3, z: 0}")
yaml_lines.append("  m_LocalScale: {x: 1, y: 1, z: 1}")
yaml_lines.append("  m_ConstrainProportionsScale: 0")
yaml_lines.append("  m_Children: []")
yaml_lines.append("  m_Father: {fileID: 0}")
yaml_lines.append("  m_LocalEulerAnglesHint: {x: 50, y: -30, z: 0}")

# HexTileContainer
yaml_lines.append("--- !u!1 &399977390")
yaml_lines.append("GameObject:")
yaml_lines.append("  m_ObjectHideFlags: 0")
yaml_lines.append("  m_CorrespondingSourceObject: {fileID: 0}")
yaml_lines.append("  m_PrefabInstance: {fileID: 0}")
yaml_lines.append("  m_PrefabAsset: {fileID: 0}")
yaml_lines.append("  serializedVersion: 6")
yaml_lines.append("  m_Component:")
yaml_lines.append("  - component: {fileID: 399977391}")
yaml_lines.append("  m_Layer: 0")
yaml_lines.append("  m_Name: HexTileContainer")
yaml_lines.append("  m_TagString: Untagged")
yaml_lines.append("  m_Icon: {fileID: 0}")
yaml_lines.append("  m_NavMeshLayer: 0")
yaml_lines.append("  m_StaticEditorFlags: 0")
yaml_lines.append("  m_IsActive: 1")
yaml_lines.append("--- !u!4 &399977391")
yaml_lines.append("Transform:")
yaml_lines.append("  m_ObjectHideFlags: 0")
yaml_lines.append("  m_CorrespondingSourceObject: {fileID: 0}")
yaml_lines.append("  m_PrefabInstance: {fileID: 0}")
yaml_lines.append("  m_PrefabAsset: {fileID: 0}")
yaml_lines.append("  m_GameObject: {fileID: 399977390}")
yaml_lines.append("  serializedVersion: 2")
yaml_lines.append("  m_LocalRotation: {x: 0, y: 0, z: 0, w: 1}")
yaml_lines.append("  m_LocalPosition: {x: 0, y: 0, z: 0}")
yaml_lines.append("  m_LocalScale: {x: 1, y: 1, z: 1}")
yaml_lines.append("  m_ConstrainProportionsScale: 0")

# Add children references (use Transform IDs, not PrefabInstance IDs)
children_refs = []
for i in range(len(tile_data)):
    child_id = 1000000002 + (i * 100)  # Transform ID (PrefabInstance ID + 2)
    children_refs.append(f"  - {{fileID: {child_id}}}")

yaml_lines.append("  m_Children:")
for child_ref in children_refs:
    yaml_lines.append(child_ref)
yaml_lines.append("  m_Father: {fileID: 0}")
yaml_lines.append("  m_LocalEulerAnglesHint: {x: 0, y: 0, z: 0}")

# Main Camera
yaml_lines.append("--- !u!1 &885549158")
yaml_lines.append("GameObject:")
yaml_lines.append("  m_ObjectHideFlags: 0")
yaml_lines.append("  m_CorrespondingSourceObject: {fileID: 0}")
yaml_lines.append("  m_PrefabInstance: {fileID: 0}")
yaml_lines.append("  m_PrefabAsset: {fileID: 0}")
yaml_lines.append("  serializedVersion: 6")
yaml_lines.append("  m_Component:")
yaml_lines.append("  - component: {fileID: 885549161}")
yaml_lines.append("  - component: {fileID: 885549160}")
yaml_lines.append("  - component: {fileID: 885549159}")
yaml_lines.append("  m_Layer: 0")
yaml_lines.append("  m_Name: Main Camera")
yaml_lines.append("  m_TagString: MainCamera")
yaml_lines.append("  m_Icon: {fileID: 0}")
yaml_lines.append("  m_NavMeshLayer: 0")
yaml_lines.append("  m_StaticEditorFlags: 0")
yaml_lines.append("  m_IsActive: 1")
yaml_lines.append("--- !u!81 &885549159")
yaml_lines.append("AudioListener:")
yaml_lines.append("  m_ObjectHideFlags: 0")
yaml_lines.append("  m_CorrespondingSourceObject: {fileID: 0}")
yaml_lines.append("  m_PrefabInstance: {fileID: 0}")
yaml_lines.append("  m_PrefabAsset: {fileID: 0}")
yaml_lines.append("  m_GameObject: {fileID: 885549158}")
yaml_lines.append("  m_Enabled: 1")
yaml_lines.append("--- !u!20 &885549160")
yaml_lines.append("Camera:")
yaml_lines.append("  m_ObjectHideFlags: 0")
yaml_lines.append("  m_CorrespondingSourceObject: {fileID: 0}")
yaml_lines.append("  m_PrefabInstance: {fileID: 0}")
yaml_lines.append("  m_PrefabAsset: {fileID: 0}")
yaml_lines.append("  m_GameObject: {fileID: 885549158}")
yaml_lines.append("  m_Enabled: 1")
yaml_lines.append("  serializedVersion: 2")
yaml_lines.append("  m_ClearFlags: 1")
yaml_lines.append("  m_BackGroundColor: {r: 0.19215687, g: 0.3019608, b: 0.4745098, a: 0}")
yaml_lines.append("  m_projectionMatrixMode: 1")
yaml_lines.append("  m_GateFitMode: 2")
yaml_lines.append("  m_FOVAxisMode: 0")
yaml_lines.append("  m_Iso: 200")
yaml_lines.append("  m_ShutterSpeed: 0.005")
yaml_lines.append("  m_Aperture: 16")
yaml_lines.append("  m_FocusDistance: 10")
yaml_lines.append("  m_FocalLength: 50")
yaml_lines.append("  m_BladeCount: 5")
yaml_lines.append("  m_Curvature: {x: 2, y: 11}")
yaml_lines.append("  m_BarrelClipping: 0.25")
yaml_lines.append("  m_Anamorphism: 0")
yaml_lines.append("  m_SensorSize: {x: 36, y: 24}")
yaml_lines.append("  m_LensShift: {x: 0, y: 0}")
yaml_lines.append("  m_NormalizedViewPortRect:")
yaml_lines.append("    serializedVersion: 2")
yaml_lines.append("    x: 0")
yaml_lines.append("    y: 0")
yaml_lines.append("    width: 1")
yaml_lines.append("    height: 1")
yaml_lines.append("  near clip plane: 0.3")
yaml_lines.append("  far clip plane: 1000")
yaml_lines.append("  field of view: 60")
yaml_lines.append("  orthographic: 0")
yaml_lines.append("  orthographic size: 5")
yaml_lines.append("  m_Depth: -1")
yaml_lines.append("  m_CullingMask:")
yaml_lines.append("    serializedVersion: 2")
yaml_lines.append("    m_Bits: 4294967295")
yaml_lines.append("  m_RenderingPath: -1")
yaml_lines.append("  m_TargetTexture: {fileID: 0}")
yaml_lines.append("  m_TargetDisplay: 0")
yaml_lines.append("  m_TargetEye: 3")
yaml_lines.append("  m_HDR: 1")
yaml_lines.append("  m_AllowMSAA: 1")
yaml_lines.append("  m_AllowDynamicResolution: 0")
yaml_lines.append("  m_ForceIntoRT: 0")
yaml_lines.append("  m_OcclusionCulling: 1")
yaml_lines.append("  m_StereoConvergence: 10")
yaml_lines.append("  m_StereoSeparation: 0.022")
yaml_lines.append("--- !u!4 &885549161")
yaml_lines.append("Transform:")
yaml_lines.append("  m_ObjectHideFlags: 0")
yaml_lines.append("  m_CorrespondingSourceObject: {fileID: 0}")
yaml_lines.append("  m_PrefabInstance: {fileID: 0}")
yaml_lines.append("  m_PrefabAsset: {fileID: 0}")
yaml_lines.append("  m_GameObject: {fileID: 885549158}")
yaml_lines.append("  serializedVersion: 2")
yaml_lines.append("  m_LocalRotation: {x: 0, y: 0, z: 0, w: 1}")
yaml_lines.append("  m_LocalPosition: {x: 0, y: 1, z: -10}")
yaml_lines.append("  m_LocalScale: {x: 1, y: 1, z: 1}")
yaml_lines.append("  m_ConstrainProportionsScale: 0")
yaml_lines.append("  m_Children: []")
yaml_lines.append("  m_Father: {fileID: 0}")
yaml_lines.append("  m_LocalEulerAnglesHint: {x: 0, y: 0, z: 0}")

# Generate HexTile prefab instances
# Prefab GUID: 8ec5c01b9c2af2049b6800fe979ee037
PREFAB_GUID = "8ec5c01b9c2af2049b6800fe979ee037"
PREFAB_INSTANCE_ID = 7018648038695141315
PREFAB_TRANSFORM_ID = 6394647473022444641

for i, (idx, q, r, layer, x, y, z) in enumerate(tile_data):
    base_id = 1000000000 + (i * 100)
    
    yaml_lines.append("--- !u!1001 &{}".format(base_id))
    yaml_lines.append("PrefabInstance:")
    yaml_lines.append("  m_ObjectHideFlags: 0")
    yaml_lines.append("  serializedVersion: 2")
    yaml_lines.append("  m_CorrespondingSourceObject: {fileID: 7018648038695141315, guid: 8ec5c01b9c2af2049b6800fe979ee037, type: 3}")
    yaml_lines.append("  m_PrefabInstance: {fileID: 0}")
    yaml_lines.append("  m_GameObject: {fileID: " + str(base_id + 1) + "}")
    yaml_lines.append("  m_Enabled: 1")
    yaml_lines.append("  m_Component:")
    yaml_lines.append("  - component: {fileID: " + str(base_id + 2) + "}")
    yaml_lines.append("  - component: {fileID: " + str(base_id + 3) + "}")
    yaml_lines.append("  - component: {fileID: " + str(base_id + 4) + "}")
    yaml_lines.append("  - component: {fileID: " + str(base_id + 5) + "}")
    yaml_lines.append("  - component: {fileID: " + str(base_id + 6) + "}")
    yaml_lines.append("  m_Layer: 0")
    yaml_lines.append("  m_Name: hextile{:03d}".format(i + 1))
    yaml_lines.append("  m_TagString: Untagged")
    yaml_lines.append("  m_Icon: {fileID: 0}")
    yaml_lines.append("  m_NavMeshLayer: 0")
    yaml_lines.append("  m_StaticEditorFlags: 0")
    yaml_lines.append("  m_IsActive: 1")
    
    # GameObject
    yaml_lines.append("--- !u!1 &{}".format(base_id + 1))
    yaml_lines.append("GameObject:")
    yaml_lines.append("  m_ObjectHideFlags: 0")
    yaml_lines.append("  m_CorrespondingSourceObject: {fileID: 7018648038695141315, guid: 8ec5c01b9c2af2049b6800fe979ee037, type: 3}")
    yaml_lines.append("  m_PrefabInstance: {fileID: " + str(base_id) + "}")
    yaml_lines.append("  m_PrefabAsset: {fileID: 0}")
    yaml_lines.append("  serializedVersion: 6")
    yaml_lines.append("  m_Component:")
    yaml_lines.append("  - component: {fileID: " + str(base_id + 2) + "}")
    yaml_lines.append("  m_Layer: 0")
    yaml_lines.append("  m_Name: HexTile")
    yaml_lines.append("  m_TagString: Untagged")
    yaml_lines.append("  m_Icon: {fileID: 0}")
    yaml_lines.append("  m_NavMeshLayer: 0")
    yaml_lines.append("  m_StaticEditorFlags: 0")
    yaml_lines.append("  m_IsActive: 1")
    
    # Transform
    yaml_lines.append("--- !u!4 &{}".format(base_id + 2))
    yaml_lines.append("Transform:")
    yaml_lines.append("  m_ObjectHideFlags: 0")
    yaml_lines.append("  m_CorrespondingSourceObject: {fileID: 6394647473022444641, guid: 8ec5c01b9c2af2049b6800fe979ee037, type: 3}")
    yaml_lines.append("  m_PrefabInstance: {fileID: " + str(base_id) + "}")
    yaml_lines.append("  m_PrefabAsset: {fileID: 0}")
    yaml_lines.append("  m_GameObject: {fileID: " + str(base_id + 1) + "}")
    yaml_lines.append("  serializedVersion: 2")
    yaml_lines.append("  m_LocalRotation: {x: -0, y: -0, z: -0, w: 1}")
    yaml_lines.append("  m_LocalPosition: {x: " + f"{x:.4f}" + ", y: " + f"{y}" + ", z: " + f"{z:.4f}" + "}")
    yaml_lines.append("  m_LocalScale: {x: 1, y: 1, z: 1}")
    yaml_lines.append("  m_ConstrainProportionsScale: 0")
    yaml_lines.append("  m_Children: []")
    yaml_lines.append("  m_Father: {fileID: 399977391}")
    yaml_lines.append("  m_LocalEulerAnglesHint: {x: 0, y: 0, z: 0}")

# Scene Roots
yaml_lines.append("--- !u!1660057539 &9223372036854775807")
yaml_lines.append("SceneRoots:")
yaml_lines.append("  m_ObjectHideFlags: 0")
yaml_lines.append("  m_Roots:")
yaml_lines.append("  - {fileID: 885549161}")
yaml_lines.append("  - {fileID: 247249175}")
yaml_lines.append("  - {fileID: 399977391}")

# Write to file
with open('Assets/GameData/Scenes/Scene_HexagonMap.unity', 'w', encoding='utf-8') as f:
    f.write('\n'.join(yaml_lines))

print(f"Generated scene with {len(tile_data)} tiles")
print("Saved to Assets/GameData/Scenes/Scene_HexagonMap.unity")
